# Generated by Django 5.0.6 on 2024-07-05 15:21

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task_2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainpage",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "header_image",
                "800x400",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
